spring:
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
    default-schema: voting-system
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/voting-system?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: root
    password: pass
invert-text:
  base-url: https://api.invertexto.com/v1
  token: ${INVERTEXT_TOKEN}